FROM rdomloge/react-build

RUN npx create-react-app react-poc

WORKDIR /react-poc/src
RUN npm i --save @fortawesome/fontawesome-svg-core
RUN npm i --save @fortawesome/free-solid-svg-icons
RUN npm i --save @fortawesome/free-regular-svg-icons
RUN npm i --save @fortawesome/free-brands-svg-icons
RUN npm i --save @fortawesome/react-fontawesome@latest