pipeline {
    
    agent { label "helm-worker" }

    parameters {
        password ( name: 'LINKSERVICE_DB_PASSWORD' generatedPassword: true )
        password ( name: 'KEYCLOAK_DB_PASSWORD' generatedPassword: true )
        string ( name: 'TENANT' )
    }

    environment {
        BUILDER = 'mybuilder'
        FOLDER = "${WORKSPACE}/jenkins-k8s-setup/helm"
    }

    stages {
        stage('Checkout') {
            steps {
                withFolderProperties() {
                    git branch: 'main', url: "https://${env.GITHUB_PERSONAL_ACCESS_TOKEN}@github.com/rdomloge/sl-k8s-scripts.git"
                }
            }
        }

        stage('Deploy platform via Helm') {
            steps {
                script {
                    withFolderProperties() {
                        withKubeConfig(credentialsId: 'prod-k8s', 
                                        serverUrl: "${env.K8S_SERVER_URL}") {

                            sh 'helm install --generate-name ${FOLDER} --set tenant=${TENANT} --set LINKSERVICE_DB_PASSWORD=${LINKSERVICE_DB_PASSWORD} --set KEYCLOAK_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}'
                        }
                    }
                }
            }
        }
    }
}