---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq-metrics
  namespace: {{ .Values.tenant }}
  labels:
    tenant: {{ .Values.tenant }}
spec:
  selector:
    matchLabels:
      component: metrics
      app: rabbit
  namespaceSelector:
    matchNames:
      - {{ .Values.tenant }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
