#spring.main.web-application-type=NONE
logging.level.com.domloge=DEBUG
logging.level.root=INFO
server.port=${server_port}
spring.data.rest.base-path=/.rest

# Max file size.
spring.servlet.multipart.max-file-size=10MB
# Max request size.
spring.servlet.multipart.max-request-size=12MB

## CURRENTLY USING AMAZON SES
spring.mail.host=${mail_host}
spring.mail.username=${mail_username}
spring.mail.password=${mail_password}
spring.mail.from=${mail_from}
spring.mail.testing.addresses=rdomloge@gmail.com
spring.mail.requestsignoff=James at Front Page Advantage & Slinky Linky
spring.mail.requestcontact=Email: james.p@frontpageadvantage.com
spring.mail.declinedWarning.addresses=${mail_declined_warning_addresses}
spring.mail.declineEmailRecipientName=${mail_declineEmailRecipientName}
spring.mail.expiredWarning.addresses=${mail_expiredWarningAddresses}
spring.mail.bccRecipients=${mail_bccRecipients}
spring.mail.testing=${spring_mail_testing}

linkService.baseUrl=${linkservice_baseurl}
slinkyLinky.domain=${slinkylinky_domain}

#spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=${spring_datasource_url}
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

#RabbitMQ settings
rabbitmq.host=10.0.0.12
rabbitmq.virtualhost=${slinkylinky_vhost}
rabbitmq.port=15672
rabbitmq.username=CHANGEME
rabbitmq.password=CHANGEME
rabbitmq.exchange=slinkylinky.exchange
rabbitmq.audit.queue=slinkylinky.audit.queue
rabbitmq.audit.routingkey=slinkylinky.audit.key
rabbitmq.supplierengagement.proposals.queue=slinkylinky.proposals.supplierengagement
rabbitmq.proposals.exchange=slinkylinky.proposals.exchange
rabbitmq.supplierengagement.queue=slinkylinky.supplierengagement.queue
rabbitmq.supplierengagement.routingkey=slinkylinky.supplierengagement.key
rabbitmq.reply.timeout=60000
rabbitmq.concurrent.consumers=1
rabbitmq.max.concurrent.consumers=1