spring.data.rest.base-path=/.rest
#spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

logging.level.org.springframework.web=INFO
logging.level.com.domloge=DEBUG
spring.datasource.url=${spring_datasource_url}

wc.key=${woocommerce_key}
wc.secret=${woocommerce_secret}
wc.base_url=${woocommerce_host}

wc.link_service_base=${wc_link_service_base}

spring.mail.from=${mail_from}


#RabbitMQ settings
rabbitmq.host=10.0.0.12
rabbitmq.virtualhost=${slinkylinky_vhost}
rabbitmq.port=15672
rabbitmq.username=CHANGEME
rabbitmq.password=CHANGEME
rabbitmq.proposals.exchange=slinkylinky.proposals.exchange
rabbitmq.woocommerce.proposals.queue=slinkylinky.proposals.woocommerce
rabbitmq.exchange=slinkylinky.exchange
rabbitmq.reply.timeout=60000
rabbitmq.concurrent.consumers=1
rabbitmq.max.concurrent.consumers=1

rabbitmq.audit.queue=slinkylinky.audit.queue
rabbitmq.audit.routingKey=slinkylinky.audit.key