spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:8080/realms/slinkylinky}
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8080/realms/slinkylinky/protocol/openid-connect/certs}