apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: slinkylinky
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: postgres
            command: ["pg_dump"]
            args: ["-h", "postgres-service", "-U", "slinkylinky", "-d", "slinkylinky", "-f", "/backup/$(echo printf `%(%Y-%m-%d_%H:%M:%S_%Z)T\n`)-backup.sql"]
            volumeMounts:
              - name: backup-volume
                mountPath: /backup
            env:
              - name: PGPASSWORD
                value: CHANGEME
          restartPolicy: OnFailure
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: sl-postgres-backup
