apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: slinkylinky
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: postgres
            command: ["/bin/sh"]
            args: ["-c", "pg_dump -h postgres-service -U slinkylinky -d slinkylinky -f /backup/$(FILENAME)-backup.sql"]
            volumeMounts:
              - name: backup-volume
                mountPath: /backup
            env:
              - name: PGPASSWORD
                value: sl
              - name: FILENAME
                value: $(date +"%Y-%m-%d_%H%M")
          restartPolicy: OnFailure
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: sl-postgres-backup
