apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es
  namespace: slinkylinky
spec:
  serviceName: es
  replicas: 1
  selector:
    matchLabels:
      app: es
      version: v1
  template:
    metadata:
      labels:
        app: es
        version: v1
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - linkservice
                      - adminwebsite
                      - postgres
                      - es
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: es
          image: elasticsearch:7.17.17
          imagePullPolicy: Always
          volumeMounts: 
            - name: sl-es-data
              mountPath: /usr/share/elasticsearch/data
          env:
            - name: discovery.type 
              value: single-node
            - name: ES_JAVA_OPTS
              value: -Xms2048m -Xmx2048m
          resources:
            requests:
              cpu: "1000m"
              memory: "2048Mi"
            limits:
              cpu: "1500m"
              memory: "2048Mi"
          ports:
            - containerPort: 9200
      volumes:
        - name: sl-es-data
          persistentVolumeClaim:
            claimName: sl-es-data