apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins
  namespace: slinkylinky
spec:
  serviceName: jenkins
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
      version: v1
  template:
    metadata:
      labels:
        app: jenkins
        version: v1
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts-jdk17
          imagePullPolicy: IfNotPresent
          volumeMounts: 
            - name: sl-jenkins-data
              mountPath: /var/jenkins_home
          env:
            - name: jenkins_PASSWORD
              value: CHANGEME
          resources:
            requests:
              cpu: "1000m"
              memory: "1024Mi"
            limits:
              cpu: "1500m"
              memory: "6000Mi"
          ports:
            - containerPort: 8080
      volumes:
        - name: sl-jenkins-data
          persistentVolumeClaim:
            claimName: sl-jenkins-data

---

# Create a Jenkins service
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: slinkylinky
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 8099
      targetPort: 8080
  #type: ClusterIP

---

# Create a persistent volume claim for Jenkins
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sl-jenkins-data
  namespace: slinkylinky
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: sl-jenkins-data
  
---
# Create a Jenkins worker deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-worker
  namespace: slinkylinky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-worker
      version: v1
  template:
    metadata:
      labels:
        app: jenkins-worker
        version: v1
    spec:
      containers:
        - name: jenkins-worker
          image: jenkins/jnlp-slave:4.3-4
          imagePullPolicy: IfNotPresent
          env:
            - name: jenkins_URL
              value: http://jenkins-service:8080
            - name: jenkins_SECRET
              value: CHANGEME
            - name: jenkins_AGENT_NAME
              value: jenkins-worker
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: jenkins-worker-home
              mountPath: /home/jenkins
      volumes:
        - name: jenkins-worker-home
          emptyDir: {}

---
# Create a Jenkins worker service
apiVersion: v1
kind: Service
metadata:
  name: jenkins-worker-service
  namespace: slinkylinky
spec:
  selector:
    app: jenkins-worker
  ports:
    - protocol: TCP
      port: 50000
      targetPort: 50000
  type: ClusterIP