kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sl-postgres-data
  namespace: slinkylinky
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi
