apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: topclick
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
            - name: backup
              image: postgres
              command: ["/bin/sh"]
              args: ["-c", "pg_dumpall --clean --if-exists --exclude-database=keycloak -h postgres-service -U ${POSTGRES_BACKUP_USER} --no-role-passwords -f /backup/$(FILENAME)-backup.sql"]
              volumeMounts:
                - name: temp-backup-volume
                  mountPath: /backup
              env:
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: db-connection-secret
                      key: POSTGRES_BACKUP_PASSWORD
                - name: POSTGRES_BACKUP_USER
                  valueFrom:
                    secretKeyRef:
                      name: db-connection-secret
                      key: POSTGRES_BACKUP_USER
                - name: FILENAME
                  value: $(date +"%Y-%m-%d_%H%M")

            - name: scp-offite
              image: rdomloge/scp-sshpass:1.0
              command: ["/bin/sh"]
              args: ["-c", "sshpass -p '${RSYNC_PASSWORD}' scp  -o 'StrictHostKeyChecking=no' -P 2222 -r /backup/ $(RSYNC_USER)@${RSYNC_HOST}:/volume1/sl-topclick-postgres-backups/"]
              imagePullPolicy: Always
              volumeMounts:
                - name: temp-backup-volume
                  mountPath: /backup
              env:
                - name: RSYNC_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: rsync-credentials
                      key: RSYNC_PASSWORD
                - name: RSYNC_USER
                  valueFrom:
                    secretKeyRef:
                      name: rsync-credentials
                      key: RSYNC_USER
                - name: RSYNC_HOST
                  valueFrom:
                    secretKeyRef:
                      name: rsync-credentials
                      key: RSYNC_HOST
          containers:
            - name: job-done
              image: busybox
              command: ['sh', '-c', 'echo "Backup and rsync completed"']
          restartPolicy: Never
          volumes:
          - name: temp-backup-volume
            emptyDir: {}
          
            