pipeline {
    
    agent { label "kubectl-worker" }

    environment {
        BUILDER = 'mybuilder'
    }

    stages {
        stage('Checkout') {
            steps {
                withFolderProperties() {
                    git branch: 'main', url: "https://${env.GITHUB_PERSONAL_ACCESS_TOKEN}@github.com/rdomloge/sl-k8s-scripts.git"
                }
            }
        }

        stage('Runonce stuff') {
            steps {
                withFolderProperties() {
                    script {
                        withKubeConfig(credentialsId: 'prod-k8s', 
                                        serverUrl: "${env.K8S_SERVER_URL}") {
                            sh 'kubectl apply -f cloudflare.yml'
                        }
                    }
                }
            }
        }
    }
}