apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  namespace: topclick
spec:
  serviceName: keycloak
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
      version: v1
  template:
    metadata:
      labels:
        app: keycloak
        version: v1
    spec:
      
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.3.4
          imagePullPolicy: Always
          args: ["start"]
          env:
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: 'KC_CACHE'
              value: 'ispn'
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_METRICS_ENABLED
              value: "true"
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: admin
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: admin
            - name: 'KC_DB_URL_DATABASE'
              value: 'keycloak'
            - name: 'KC_DB_URL_HOST'
              value: 'postgres-service'
            - name: 'KC_DB'
              value: 'keycloak'
            # In a production environment, use a secret to store username and password to the database
            - name: 'KC_DB_PASSWORD'
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: KC_DB_PASSWORD
            - name: 'KC_DB_USERNAME'
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: KC_DB_USERNAME
          resources:
            requests:
              cpu: "500m"
              memory: "1700Mi"
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /health/started
              port: 9000
            periodSeconds: 1
            failureThreshold: 600              
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9000
            periodSeconds: 10
            failureThreshold: 3              
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9000
            periodSeconds: 10
            failureThreshold: 3