apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  namespace: topclick
spec:
  serviceName: keycloak
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
      version: v1
  template:
    metadata:
      labels:
        app: keycloak
        version: v1
    spec:
      
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.0.2
          imagePullPolicy: Always
          args: ["start"]
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: admin
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: admin
            - name: db-url
              valueFrom:
                secretKeyRef:
                  name: db-connection-secret
                  key: KEYCLOAK_DATABASE_URL
            - name: db-username
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: DB_USERNAME
            - name: db-password
              valueFrom:  
                secretKeyRef:
                  name: keycloak-credentials
                  key: DB_PASSWORD  
          resources:
            requests:
              cpu: "1000m"
              memory: "1500Mi"
          ports:
            - containerPort: 8080
            - containerPort: 9000
          startupProbe:
              tcpSocket:
                port: 8080
              initialDelaySeconds: 20
              failureThreshold: 5
              periodSeconds: 10
          # livenessProbe:
          #     httpGet:
          #       path: /health/live
          #       port: 9000
          # readinessProbe:
          #     httpGet:
          #       path: /health/ready
          #       port: 9000