spring.data.rest.base-path=/.rest
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none

management.endpoint.health.probes.enabled=true

logging.level.org.springframework.web=INFO
logging.level.com.domloge=DEBUG
#logging.level.ROOT=DEBUG
#logging.level.sun.rmi=INFO
#logging.level.javax.management=INFO
spring.datasource.url=${spring_datasource_url:jdbc:h2:mem:woodb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE}

wc.key=${woocommerce_key:local-key}
wc.secret=${woocommerce_secret:local-secret}
wc.base_url=${woocommerce_host:http://localhost}
wc.uploads_base=${wc_uploads_base:http://localhost/uploads}

wc.link_service_base=${wc_link_service_base:http://localhost:8090}
linkservice_url=${linkservice_url:http://localhost:8090}

spring.mail.from=${mail_from:no-reply@localhost}


#RabbitMQ settings
rabbitmq.host=rabbit-service
rabbitmq.virtualhost=${slinkylinky_vhost:slinkylinky}
rabbitmq.port=15672
rabbitmq.username=${slinkylinky_rabbitmq_username:guest}
rabbitmq.password=${slinkylinky_rabbitmq_password:guest}
rabbitmq.proposals.exchange=slinkylinky.proposals.exchange
rabbitmq.woocommerce.proposals.queue=slinkylinky.proposals.woocommerce
rabbitmq.exchange=slinkylinky.exchange
rabbitmq.reply.timeout=60000
rabbitmq.concurrent.consumers=1
rabbitmq.max.concurrent.consumers=1

rabbitmq.audit.queue=slinkylinky.audit.queue
rabbitmq.audit.routingKey=slinkylinky.audit.key