#!/usr/bin/env node
/**
 * gen-docs.js — SlinkyLinky codebase index generator
 *
 * Generates markdown reference files under docs/ to enable efficient
 * Claude Code work without repetitive scanning.
 *
 * Usage (from repo root):
 *   node scripts/gen-docs.js
 *
 * From frontend:
 *   npm run gen-docs
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const FRONTEND_SRC = path.join(ROOT, 'frontend', 'react', 'src');
const DOCS_DIR = path.join(ROOT, 'docs');
const GENERATED_NOTE = '> Auto-generated by `scripts/gen-docs.js` — run `node scripts/gen-docs.js` to refresh.\n\n';

if (!fs.existsSync(DOCS_DIR)) fs.mkdirSync(DOCS_DIR);

// ─────────────────────────────────────────────
// Utilities
// ─────────────────────────────────────────────

function readFile(p) {
  try { return fs.readFileSync(p, 'utf8'); } catch { return null; }
}

function writeDoc(name, content) {
  const p = path.join(DOCS_DIR, name);
  fs.writeFileSync(p, content, 'utf8');
  console.log(`  wrote ${path.relative(ROOT, p).replace(/\\/g, '/')}`);
}

function walkDir(dir, exts) {
  const results = [];
  if (!fs.existsSync(dir)) return results;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...walkDir(full, exts));
    } else if (exts.some(e => entry.name.endsWith(e))) {
      results.push(full);
    }
  }
  return results;
}

function rel(p) {
  return path.relative(ROOT, p).replace(/\\/g, '/');
}

function relSrc(p) {
  return path.relative(FRONTEND_SRC, p).replace(/\\/g, '/');
}

// ─────────────────────────────────────────────
// Frontend: Component Analysis
// ─────────────────────────────────────────────

function analyzeJsxFile(filePath) {
  const src = readFile(filePath);
  if (!src) return null;

  const file = relSrc(filePath);

  // Component name — prefer explicit named default export, fall back to filename
  let name =
    (src.match(/export default function (\w+)/) ||
     src.match(/^function (\w+)[^{]*\{[\s\S]*\nexport default \1/m) ||
     src.match(/const (\w+)\s*=\s*\(/) && src.includes(`export default ${src.match(/const (\w+)\s*=\s*\(/)?.[1]}`)
    )?.[1] || path.basename(filePath, path.extname(filePath));

  // Also try: export default SomeName at the bottom
  const bottomExport = src.match(/export default (\w+)\s*;?\s*$/m);
  if (bottomExport && bottomExport[1] !== 'function') name = bottomExport[1];
  // Re-check named export
  const namedDefault = src.match(/export default function (\w+)/);
  if (namedDefault) name = namedDefault[1];

  // Description — first JSDoc block or first line comment before component
  let description = '';
  const jsdoc = src.match(/\/\*\*([\s\S]*?)\*\//);
  if (jsdoc) {
    description = jsdoc[1]
      .split('\n')
      .map(l => l.replace(/^\s*\*\s?/, '').trim())
      .filter(Boolean)
      .join(' ');
  }

  // Props — from destructured function parameter
  const propsMatch = src.match(/(?:export default )?function \w*\s*\(\s*\{([^}]+)\}/);
  const props = propsMatch
    ? propsMatch[1]
        .split(',')
        .map(p => p.split('=')[0].trim().replace(/\n/g, ''))
        .filter(p => p && /^\w+$/.test(p))
    : [];

  // Local component imports from @/components or relative
  const importedComponents = [
    ...src.matchAll(/import\s+(?:\{[^}]+\}|\w+)\s+from\s+['"]@\/components\/([^'"]+)['"]/g),
  ].map(m => m[0].match(/import\s+(?:\{([^}]+)\}|(\w+))/)?.[1] || m[0].match(/import\s+(\w+)/)?.[1] || '')
   .filter(Boolean)
   .flatMap(s => s.split(',').map(x => x.trim()))
   .filter(Boolean);

  // API calls — fetch/fetchWithAuth patterns
  const apiCalls = [
    ...new Set([
      ...[...src.matchAll(/fetch(?:WithAuth)?\s*\(\s*['"`]([^'"`]+)['"`]/g)].map(m => m[1]),
      ...[...src.matchAll(/fetch(?:WithAuth)?\s*\(\s*`([^`$]+)/g)].map(m => m[1] + '…'),
    ])
  ].filter(u => u.startsWith('/') || u.startsWith('.'));

  // Whether it's a page (uses Layout) or atom
  const usesLayout = /import.*Layout/.test(src);

  return { name, file, description, props, importedComponents, apiCalls, usesLayout };
}

// ─────────────────────────────────────────────
// Frontend: Route Extraction from App.jsx
// ─────────────────────────────────────────────

function extractRoutes() {
  const src = readFile(path.join(FRONTEND_SRC, 'App.jsx'));
  if (!src) return [];
  const routes = [];
  for (const m of src.matchAll(/<Route\s+path="([^"]+)"\s+element=\{<(\w+)\s*/g)) {
    routes.push({ path: m[1], component: m[2] });
  }
  // Map component names back to page files
  const importMap = {};
  for (const m of src.matchAll(/import (\w+) from '@\/pages\/([^']+)'/g)) {
    importMap[m[1]] = `pages/${m[2]}.jsx`;
  }
  return routes.map(r => ({ ...r, file: importMap[r.component] || '' }));
}

// ─────────────────────────────────────────────
// Backend: JPA Entity Analysis
// ─────────────────────────────────────────────

function analyzeJavaEntity(filePath) {
  const src = readFile(filePath);
  if (!src || !src.includes('@Entity')) return null;

  const name = path.basename(filePath, '.java');

  const tableMatch = src.match(/@Table\s*\([^)]*name\s*=\s*"([^"]+)"/);
  const table = tableMatch ? tableMatch[1] : name.toLowerCase() + 's';

  // Primitive/simple fields: private Type field;
  const fields = [];
  for (const m of src.matchAll(/private\s+((?:String|int|long|boolean|double|float|LocalDate(?:Time)?|BigDecimal|Integer|Long|List<[^>]+>))\s+(\w+)\s*;/g)) {
    fields.push(`${m[2]}: ${m[1]}`);
  }

  // Relationships
  const rels = [];
  for (const m of src.matchAll(/@(ManyToOne|OneToMany|ManyToMany|OneToOne)[\s\S]*?private\s+\S+\s+(\w+)\s*;/g)) {
    rels.push(`${m[2]} (${m[1]})`);
  }

  return { name, table, fields, rels };
}

// ─────────────────────────────────────────────
// Backend: Controller Analysis
// ─────────────────────────────────────────────

function analyzeJavaController(filePath) {
  const src = readFile(filePath);
  if (!src) return null;
  if (!src.includes('@RestController') && !src.includes('@Controller')) return null;

  const name = path.basename(filePath, '.java');
  const basePath = src.match(/@RequestMapping\s*\(\s*(?:value\s*=\s*|path\s*=\s*)?["']([^"']+)["']/)?.[1] || '';

  // Line-by-line pass: more robust against intervening annotations
  const lines = src.split('\n');
  const endpoints = [];
  const HTTP_METHODS = ['Get', 'Post', 'Put', 'Delete', 'Patch'];

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();

    // Detect a method-level mapping annotation
    const mapMatch = line.match(/@(Get|Post|Put|Delete|Patch)Mapping/);
    if (!mapMatch) continue;

    const httpMethod = mapMatch[1].toUpperCase();

    // Extract sub-path from same line (handles multi-attribute annotations)
    // Collect full annotation (may span multiple lines if not closed yet)
    let annotationText = line;
    let j = i;
    while (!annotationText.includes(')') && j < lines.length - 1) {
      j++;
      annotationText += ' ' + lines[j].trim();
    }
    const subPathMatch = annotationText.match(/(?:path|value)\s*=\s*["']([^"']*)["']/) ||
                         annotationText.match(/@\w+Mapping\s*\(\s*["']([^"']*)["']/);
    const subPath = subPathMatch ? subPathMatch[1] : '';

    // Look forward past other annotations to find public/protected method signature
    let methodName = null;
    for (let k = i + 1; k < Math.min(i + 8, lines.length); k++) {
      const ml = lines[k].trim();
      const methodMatch = ml.match(/^(?:public|protected)\s+\S+(?:<[^>]*>)?\s+(\w+)\s*\(/);
      if (methodMatch) { methodName = methodMatch[1]; break; }
    }
    if (!methodName) continue;

    const fullPath = (basePath + (subPath ? '/' + subPath : ''))
      .replace(/\/\//g, '/').replace(/^(?!\/)/, '/');

    endpoints.push({ method: httpMethod, subPath, methodName, fullPath });
  }

  return { name, basePath, endpoints, file: rel(filePath) };
}

// ─────────────────────────────────────────────
// Document Generators
// ─────────────────────────────────────────────

function genFrontendComponents(components, pages) {
  let md = `# Frontend Components\n\n${GENERATED_NOTE}`;

  // ── Atoms ──
  const atoms = components.filter(c => c.file.startsWith('components/atoms/'));
  if (atoms.length) {
    md += `## Atoms\n\nSmall, reusable UI primitives in \`src/components/atoms/\`.\n\n`;
    md += `| Component | File | Props | Notes |\n|-----------|------|-------|-------|\n`;
    for (const c of atoms) {
      const props = c.props.length ? c.props.join(', ') : '—';
      md += `| \`${c.name}\` | \`${c.file}\` | ${props} | ${c.description || ''} |\n`;
    }
    md += '\n';
  }

  // ── Layout ──
  const layout = components.filter(c => c.file.startsWith('components/layout/'));
  if (layout.length) {
    md += `## Layout\n\nLayout wrappers in \`src/components/layout/\`.\n\n`;
    md += `| Component | File | Notes |\n|-----------|------|-------|\n`;
    for (const c of layout) {
      md += `| \`${c.name}\` | \`${c.file}\` | ${c.description || ''} |\n`;
    }
    md += '\n';
  }

  // ── Feature Components ──
  const feature = components.filter(
    c => !c.file.startsWith('components/atoms/') && !c.file.startsWith('components/layout/')
  );
  if (feature.length) {
    md += `## Feature Components\n\nDomain-specific components in \`src/components/\`.\n\n`;
    for (const c of feature) {
      md += `### \`${c.name}\`\n`;
      md += `**File:** \`${c.file}\`  \n`;
      if (c.description) md += `${c.description}  \n`;
      if (c.props.length) md += `**Props:** \`${c.props.join('`, `')}\`  \n`;
      if (c.importedComponents.length) md += `**Uses:** ${c.importedComponents.join(', ')}  \n`;
      if (c.apiCalls.length) md += `**API calls:** \`${c.apiCalls.join('`, `')}\`  \n`;
      md += '\n';
    }
  }

  // ── Pages ──
  md += `## Pages\n\nRoute-level page components in \`src/pages/\`.\n\n`;
  md += `| Page | File | Props/API |\n|------|------|-----------|\n`;
  for (const p of pages) {
    const notes = [
      p.props.length ? `props: ${p.props.join(', ')}` : '',
      p.apiCalls.length ? `calls: ${p.apiCalls.slice(0, 2).join(', ')}` : '',
    ].filter(Boolean).join(' | ');
    md += `| \`${p.name}\` | \`${p.file}\` | ${notes || '—'} |\n`;
  }
  md += '\n';

  return md;
}

function genFrontendPages(routes, pages) {
  let md = `# Frontend Routes & Pages\n\n${GENERATED_NOTE}`;

  md += `## Route Table\n\nDefined in \`frontend/react/src/App.jsx\`.\n\n`;
  md += `| Path | Component | Page File | Auth |\n|------|-----------|-----------|------|\n`;

  const publicPaths = new Set(['/callback', '/public/supplierresponse', '/public/leadresponse']);
  for (const r of routes) {
    const auth = publicPaths.has(r.path) ? 'Public' : 'Protected';
    md += `| \`${r.path}\` | \`${r.component}\` | \`${r.file || '?'}\` | ${auth} |\n`;
  }
  md += '\n';

  md += `## Auth / Session\n\n`;
  md += `- Auth managed by \`src/auth/AuthProvider.jsx\` (Keycloak OIDC)\n`;
  md += `- OAuth callback handled at \`/callback\` → \`src/auth/Callback.jsx\`\n`;
  md += `- All protected routes require valid JWT; use \`useAuth()\` hook from \`AuthProvider\`\n`;
  md += `- Authenticated fetch calls should use \`fetchWithAuth\` from \`@/utils/fetchWithAuth\`\n\n`;

  md += `## Page Notes\n\n`;
  for (const p of pages) {
    const route = routes.find(r => r.component === p.name || r.file?.includes(p.file.replace('pages/', '')));
    md += `### \`${p.name}\` — \`${route?.path || p.file}\`\n`;
    if (p.description) md += `${p.description}\n`;
    if (p.apiCalls.length) md += `**API:** \`${p.apiCalls.join('`, `')}\`\n`;
    if (p.props.length) md += `**Props:** ${p.props.join(', ')}\n`;
    md += '\n';
  }

  return md;
}

function genBackendEntities(entities) {
  let md = `# Backend Domain Entities\n\n${GENERATED_NOTE}`;
  md += `All JPA entities across all services.\n`;
  md += `Schema is **not** managed by Hibernate — DDL lives in \`sl-k8s-scripts/jenkins-k8s-setup/helm/*-backup.sql\`.\n\n`;

  for (const e of entities) {
    md += `## \`${e.name}\`\n`;
    md += `**Table:** \`${e.table}\`\n\n`;
    if (e.fields.length) {
      md += `**Fields:**\n`;
      for (const f of e.fields) md += `- \`${f}\`\n`;
      md += '\n';
    }
    if (e.rels.length) {
      md += `**Relationships:**\n`;
      for (const r of e.rels) md += `- ${r}\n`;
      md += '\n';
    }
  }

  return md;
}

function genBackendApi(controllers) {
  let md = `# Backend API Endpoints\n\n${GENERATED_NOTE}`;
  md += `Base path for all services: \`/.rest\` (proxied by Vite in dev, Cloudflare Tunnel in prod).\n\n`;
  md += `Spring Data REST auto-exposes CRUD at \`/.rest/{entityPluralName}\` — only *custom* controllers are listed here.\n\n`;

  for (const c of controllers) {
    if (!c.endpoints.length) continue;
    md += `## \`${c.name}\`\n`;
    md += `**Base path:** \`${c.basePath || '(Spring Data REST)'}\`  \n`;
    md += `**File:** \`${c.file}\`\n\n`;
    md += `| Method | Path | Handler |\n|--------|------|--------|\n`;
    for (const e of c.endpoints) {
      md += `| \`${e.method}\` | \`${e.fullPath || e.subPath || '/'}\` | \`${e.methodName}()\` |\n`;
    }
    md += '\n';
  }

  // Document the Spring Data REST auto-exposed repos
  md += `## Spring Data REST (auto-exposed)\n\n`;
  md += `The following resources are auto-exposed at \`/.rest/{path}\` by Spring Data REST:\n\n`;
  md += `| Resource | Base URL | Service |\n|----------|----------|---------|\n`;
  md += `| Demand | \`/.rest/demands\` | linkservice |\n`;
  md += `| DemandSite | \`/.rest/demandSites\` | linkservice |\n`;
  md += `| Supplier | \`/.rest/suppliers\` | linkservice |\n`;
  md += `| Proposal | \`/.rest/proposals\` | linkservice |\n`;
  md += `| PaidLink | \`/.rest/paidLinks\` | linkservice |\n`;
  md += `| Category | \`/.rest/categories\` | linkservice |\n`;
  md += `| BlackListedSupplier | \`/.rest/blackListedSuppliers\` | linkservice |\n`;
  md += `| Engagement | \`/.rest/engagements\` | supplierengagement |\n`;
  md += `| SupplierLead | \`/.rest/leads\` | supplierengagement |\n`;
  md += `| AuditRecord | \`/.rest/auditrecords\` | audit |\n`;
  md += `| Stats | \`/.rest/stats\` | stats |\n`;

  return md;
}

// ─────────────────────────────────────────────
// Main
// ─────────────────────────────────────────────

console.log('Generating SlinkyLinky docs index...\n');

// Frontend
const compFiles = walkDir(path.join(FRONTEND_SRC, 'components'), ['.jsx', '.js']);
const components = compFiles.map(analyzeJsxFile).filter(Boolean);

const pageFiles = walkDir(path.join(FRONTEND_SRC, 'pages'), ['.jsx']);
const pages = pageFiles.map(analyzeJsxFile).filter(Boolean);

const routes = extractRoutes();

writeDoc('frontend-components.md', genFrontendComponents(components, pages));
writeDoc('frontend-pages.md', genFrontendPages(routes, pages));

// Backend — entities across all services
const entityDirs = ['linkservice', 'supplierengagement', 'stats', 'audit']
  .map(svc => path.join(ROOT, svc, 'src', 'main', 'java'));
const javaFiles = entityDirs.flatMap(d => walkDir(d, ['.java']));
const entities = javaFiles.map(analyzeJavaEntity).filter(Boolean);
writeDoc('backend-entities.md', genBackendEntities(entities));

// Backend — controllers (linkservice + other services)
const services = ['linkservice', 'stats', 'audit', 'supplierengagement'];
const controllers = [];
for (const svc of services) {
  const svcDir = path.join(ROOT, svc, 'src', 'main', 'java');
  const files = walkDir(svcDir, ['.java']);
  controllers.push(...files.map(analyzeJavaController).filter(Boolean));
}
writeDoc('backend-api.md', genBackendApi(controllers));

// ─────────────────────────────────────────────
// Sync CLAUDE.md Quick Reference table
// ─────────────────────────────────────────────

const GENERATED_DOCS = [
  { file: 'docs/frontend-components.md', desc: 'Every React component: file path, props, API calls, sub-components used' },
  { file: 'docs/frontend-pages.md',      desc: 'Full route table (path → component → file, auth status) and per-page API calls' },
  { file: 'docs/backend-entities.md',    desc: 'All JPA entities with fields and relationships' },
  { file: 'docs/backend-api.md',         desc: 'All custom REST endpoints by controller + Spring Data REST auto-exposed resources' },
];

function buildGeneratedTable() {
  const rows = GENERATED_DOCS
    .map(({ file, desc }) => `| [\`${file}\`](${file}) | ${desc} |`)
    .join('\n');
  return `<!-- GENERATED-DOCS-TABLE:START — managed by scripts/gen-docs.js; do not edit this block manually -->\n| File | What it covers |\n|------|----------------|\n${rows}\n<!-- GENERATED-DOCS-TABLE:END -->`;
}

const claudeMdPath = path.join(ROOT, 'CLAUDE.md');
const claudeSrc = readFile(claudeMdPath);
if (claudeSrc) {
  const updated = claudeSrc.replace(
    /<!-- GENERATED-DOCS-TABLE:START[\s\S]*?GENERATED-DOCS-TABLE:END -->/,
    buildGeneratedTable()
  );
  if (updated !== claudeSrc) {
    fs.writeFileSync(claudeMdPath, updated, 'utf8');
    console.log('  updated CLAUDE.md Quick Reference table');
  }
}

console.log('\nDone. Reference these in CLAUDE.md under docs/');
