apiVersion: apps/v1
kind: Deployment
metadata:
  name: woo
  namespace: slinkylinky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: woo
      version: v1
  template:
    metadata:
      labels:
        app: woo
        version: v1
    spec:
      containers:
        - name: woo
          image: rdomloge/slinky-linky-woocommerce:5.5.1-CI-2
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "2000m"
              memory: "2048Mi"
          ports:
            - containerPort: 8080
          env:
            - name: spring_datasource_url
              valueFrom:
                secretKeyRef:
                  name: db-connection-secret
                  key: WOOCOMMERCE_DATABASE_URL
            - name: server_port
              value: "8080"
            - name: slinkylinky_vhost
              value: slinkylinky
            - name: woocommerce_key
              value: <SPECIFY>
            - name: woocommerce_secret
              value: <SPECIFY>
            - name: woocommerce_host
              value: <SPECIFY>
            - name: linkservice_url
              value: http://linkservice-service:8090
            - name: wc_uploads_base
              value: https://link-sync.co.uk/wp-content/uploads/woocommerce_uploads/cart
          startupProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            failureThreshold: 30
            periodSeconds: 2
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
            failureThreshold: 2
            periodSeconds: 2
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            failureThreshold: 2
            periodSeconds: 2
            timeoutSeconds: 1
