GET {{host}}/bloggers
###
POST {{host}}/bloggers
Content-Type: application/json

{"name": "Thrifty Bride",
"email": "hello@thethriftybride.co.uk",
"categories": ["WEDDINGS", "BUSINESS"] }
###
POST {{host}}/bloggers
Content-Type: application/json

{"name": "Katrina Rohman",
"email": "rohmankatrina@gmail.com",
"categories": ["WEDDINGS", "BUSINESS"] }
###
GET {{host}}/bloggers/1
###
GET {{host}}/bloggers/search/findByCategories_NameIn?categories=Weddings,Pets
###
GET {{host}}/bloggers/search/findByCategories_NameIn?categories=Pets
###
GET {{host}}/bloggers/search/findByCategories_NameIn?categories=Family
###
GET {{host}}/bloggers/search/findByCategories_NameInWithAvailability?categories=Family&linkDemandId=1&daNeeded=15