GET {{host}}/linkdemands
###
POST {{host}}/linkdemands
Content-Type: application/json

{"name": "Berkley Castle Wewddings",
"email": "www.berkeleycastleweddings.co.uk",
"categories": ["WEDDINGS", "BUSINESS"] }
###
POST {{host}}/linkdemands
Content-Type: application/json

{"name": "Hedsor House",
"email": "www.hedsor.com",
"categories": ["WEDDINGS", "BUSINESS"] }
###
GET {{host}}/linkdemands/2
###
GET {{host}}/linkdemands/search/findDemandForSupplierId?supplierId=120&linkdemandIdToIgnore=5