GET {{woocommerce_host}}/orders?page=1&per_page=10
Authorization: Basic {{woocommerce_key}} {{woocommerce_secret}}
###
GET {{woocommerce_host}}/orders
Authorization: Basic {{woocommerce_key}} {{woocommerce_secret}}
###
GET {{woocommerce_host}}/orders/285
Authorization: Basic {{woocommerce_key}} {{woocommerce_secret}}
###
https://link-sync.co.uk/wp-content/uploads/woocommerce_uploads/cart/2024-02-21-04fd7d9ad5616c4315ce52f4fde4f30a.csv
###
GET {{woocommerce_host}}/orders/297
Authorization: Basic {{woocommerce_key}} {{woocommerce_secret}}
###
https://link-sync.co.uk/wp-content/uploads/woocommerce_uploads/cart/2024-02-20-415f1f53e797b633ccda0a0d4c3af103.csv
###
https://link-sync.co.uk/wp-content/uploads/woocommerce_uploads/cart/2024-02-20-415f1f53e797b633ccda0a0d4c3af103.csv
###
https://link-sync.co.uk/wp-content/uploads/woocommerce_uploads/cart/2024-02-21-415f1f53e797b633ccda0a0d4c3af103.csv
###
GET https://link-sync.co.uk/wp-json/wc/v3/customers/3
Authorization: Basic {{woocommerce_key}} {{woocommerce_secret}}
###
PUT https://example.com/wp-json/wc/v3/orders/727
Authorization: Basic {{{{woocommerce_key}}}} {{password}}
Content-Type: application/json

{
  "status": "completed"
}