GET {{host}}/linkdemands
###
POST {{host}}/linkdemands
Content-Type: application/json

{"name": "Berkley Castle Wewddings",
    "url": "www.dcwhite.co.uk",
    "daNeeded": 10,
    "anchorText": "Engineering Consultants",
    "domain": "dcwhite.co.uk",
    "requested": "27/11/2023",
    "requestedDate": "2023-11-27",
    "categories": ["http://localhost:8080/categories/42", "http://localhost:8080/categories/4"] }
###
POST {{host}}/linkdemands
Content-Type: application/json

{"name": "Murder She Wrote Retirement Home",
    "url": "www.murdersw.co.uk",
    "daNeeded": 11,
    "anchorText": "Come stay with us",
    "domain": "murdersw.co.uk",
    "requested": "26/11/2023",
    "requestedDate": "2023-11-26",
    "categories": ["http://localhost:8080/categories/5", "http://localhost:8080/categories/4"] }
###
POST {{host}}/linkdemands
Content-Type: application/json

{"name": "Ricks Rentals",
    "url": "www.ricksrentals.co.uk",
    "daNeeded": 12,
    "anchorText": "Come stay with us",
    "domain": "ricksrentals.co.uk",
    "requested": "25/11/2023",
    "requestedDate": "2023-11-25",
    "categories": ["http://localhost:8080/categories/6", "http://localhost:8080/categories/4"] }
###
POST {{host}}/linkdemands
Content-Type: application/json

{"name": "Carlas Clean Crew",
    "url": "www.carlascc.co.uk",
    "daNeeded": 13,
    "anchorText": "Squeaky Clean Carla",
    "domain": "carlascc.co.uk",
    "requested": "24/11/2023",
    "requestedDate": "2023-11-24",
    "categories": ["http://localhost:8080/categories/8", "http://localhost:8080/categories/4"] }

###
GET {{host}}/linkdemands/2
###
GET {{host}}/linkdemands/search/findDemandForSupplierId?supplierId=1&linkdemandIdToIgnore=4
###
GET {{host}}/linkdemands/search/findUnsatisfiedDemand