GET http://localhost:8084/.rest/orders
###
GET http://localhost:8084/.rest/profile
###
GET http://localhost:8084/.rest/orders?projection=lightOrder
###
GET http://localhost:8084/.rest/orders/search/findByLineItems_demandIdEquals?demandId=1
###
GET http://localhost:8084/.rest/orders/252?projection=lightOrder
###
POST http://localhost:8084/.rest/orders/webhooks/ordercreated