apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminwebsite
  namespace: slinkylinky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminwebsite
      version: v1
  template:
    metadata:
      labels:
        app: adminwebsite
        version: v1
    spec:
      containers:
        - name: adminwebsite
          image: rdomloge/slinky-linky-adminwebsite:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "96Mi"
            limits:
              cpu: "4000m"
              memory: "256Mi"
          ports:
            - containerPort: 3000
          startupProbe:
            httpGet:
              path: /demand
              port: 3000
            initialDelaySeconds: 10
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 5
