apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit
  namespace: slinkylinky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit
      version: v1
  template:
    metadata:
      labels:
        app: audit
        version: v1
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - linkservice
                      - supplierengagement
                      - audit
                      - adminwebsite
                      - postgres
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: audit
          image: rdomloge/slinky-linky-audit:3.4
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "2000m"
              memory: "2048Mi"
          ports:
            - containerPort: 8080
          env:
            - name: spring_datasource_url
              value: <SPECIFY>
            - name: server_port
              value: "8080"
            - name: slinkylinky_vhost
              value: slinkylinky
          startupProbe:
            httpGet:
              path: /.rest/auditrecords
              port: 8080
            initialDelaySeconds: 60
            failureThreshold: 30
            periodSeconds: 2
            timeoutSeconds: 2
