apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkservice
  namespace: slinkylinky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkservice
      version: v1
  template:
    metadata:
      labels:
        app: linkservice
        version: v1
    spec:
      containers:
        - name: linkservice
          image: rdomloge/slinky-linky-linkservice:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "750m"
              memory: "1024Mi"
          ports:
            - containerPort: 8080
          env:
            - name: LOGLEVEL
              value: "INFO"
          startupProbe:
            httpGet:
              path: /categories
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 2
            timeoutSeconds: 2
