apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkservice
  namespace: slinkylinky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkservice
      version: v1
  template:
    metadata:
      labels:
        app: linkservice
        version: v1
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - linkservice
                      - adminwebsite
                      - postgres
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: linkservice
          image: rdomloge/slinky-linky-linkservice:1.2
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "2000m"
              memory: "2048Mi"
          ports:
            - containerPort: 8080
          env:
            - name: spring_datasource_url
              value: jdbc:postgresql://postgres-service:5432/slinkylinky?user=slinkylinky&password=sl
          startupProbe:
            httpGet:
              path: /.rest/categories
              port: 8080
            initialDelaySeconds: 60
            failureThreshold: 30
            periodSeconds: 2
            timeoutSeconds: 2
