apiVersion: apps/v1
kind: Deployment
metadata:
  name: supplierengagement
  namespace: slinkylinky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supplierengagement
      version: v1
  template:
    metadata:
      labels:
        app: supplierengagement
        version: v1
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - linkservice
                      - supplierengagement
                      - adminwebsite
                      - postgres
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: supplierengagement
          image: rdomloge/slinky-linky-supplierengagement:1.9
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "2000m"
              memory: "2048Mi"
          ports:
            - containerPort: 8080
          env:
            - name: spring_datasource_url
              value: <SPECIFY>
            - name: server_port
              value: "8080"
            - name: mail_username
              value: <SPECIFY>
            - name: mail_password
              value: <SPECIFY>
            - name: slinkylinky_domain
              value: slinkylinky.uk
          startupProbe:
            httpGet:
              path: /.rest/engagements
              port: 8080
            initialDelaySeconds: 60
            failureThreshold: 30
            periodSeconds: 2
            timeoutSeconds: 2
